"""Travel & Places Around the World - evergreen, all-country content bank."""
from __future__ import annotations
from collections import OrderedDict


def build() -> dict:
    word_pools = OrderedDict([
        ("Countries", [
            "BRAZIL", "FRANCE", "JAPAN", "INDIA", "CHINA", "EGYPT", "ITALY",
            "SPAIN", "CANADA", "MEXICO", "KENYA", "CHILE", "PERU", "SWEDEN",
            "NORWAY", "GREECE", "TURKEY", "RUSSIA", "POLAND", "CUBA",
            "THAILAND", "VIETNAM", "ICELAND", "PORTUGAL", "IRELAND",
            "MOROCCO", "ARGENTINA", "AUSTRALIA", "INDONESIA", "MALAYSIA",
            "ENGLAND", "SCOTLAND", "GERMANY", "BELGIUM", "AUSTRIA",
            "NIGERIA", "ETHIOPIA", "COLOMBIA", "ECUADOR", "NEPAL", "BHUTAN",
            "IRAN", "IRAQ", "JORDAN", "LEBANON", "ISRAEL", "OMAN", "YEMEN",
            "QATAR", "KUWAIT", "BAHRAIN", "CYPRUS", "MALTA", "SUDAN", "CHAD",
            "MALI", "GHANA", "TOGO", "BENIN", "GABON", "ANGOLA", "UGANDA",
            "RWANDA", "CONGO", "ZAMBIA", "ZIMBABWE", "BOTSWANA", "NAMIBIA",
            "TANZANIA", "SENEGAL", "CAMEROON", "BURUNDI", "LIBYA", "TUNISIA",
            "ALGERIA", "ALBANIA", "CROATIA", "SERBIA", "SLOVENIA",
            "SLOVAKIA", "ROMANIA", "BULGARIA", "HUNGARY", "DENMARK",
            "FINLAND", "SWITZERLAND", "NETHERLANDS", "LUXEMBOURG", "MONACO",
            "ANDORRA", "LATVIA", "LITHUANIA", "ESTONIA", "UKRAINE",
            "BELARUS", "MOLDOVA", "GEORGIA", "ARMENIA", "AZERBAIJAN",
            "KAZAKHSTAN", "UZBEKISTAN", "MONGOLIA", "CAMBODIA", "LAOS",
            "MYANMAR", "BRUNEI", "SINGAPORE", "PHILIPPINES", "FIJI", "TONGA",
            "SAMOA", "PANAMA", "JAMAICA", "BARBADOS", "GRENADA", "URUGUAY",
            "PARAGUAY", "BOLIVIA", "VENEZUELA", "HONDURAS", "GUATEMALA",
            "SALVADOR", "MALDIVES", "SEYCHELLES", "MAURITIUS", "MADAGASCAR",
        ]),
        ("Capitals", [
            "PARIS", "LONDON", "TOKYO", "CAIRO", "ROME", "MADRID", "ATHENS",
            "BERLIN", "MOSCOW", "BEIJING", "DELHI", "BANGKOK", "HANOI",
            "OSLO", "STOCKHOLM", "DUBLIN", "LISBON", "VIENNA", "OTTAWA",
            "LIMA", "NAIROBI", "SEOUL", "TEHRAN", "BAGHDAD", "DAMASCUS",
            "TUNIS", "HAVANA", "SANTIAGO", "QUITO", "BUDAPEST", "WARSAW",
            "PRAGUE", "HELSINKI", "COPENHAGEN", "REYKJAVIK", "CANBERRA",
            "KABUL", "BAKU", "TBILISI", "YEREVAN", "TASHKENT", "ASTANA",
            "BISHKEK", "DUSHANBE", "KATHMANDU", "COLOMBO", "DHAKA",
            "ISLAMABAD", "AMMAN", "BEIRUT", "JERUSALEM", "DOHA", "MANAMA",
            "MUSCAT", "SANA", "RIYADH", "KHARTOUM", "DJIBOUTI", "ASMARA",
            "KAMPALA", "KIGALI", "BUJUMBURA", "LUANDA", "HARARE", "LUSAKA",
            "GABORONE", "WINDHOEK", "LOME", "COTONOU", "YAOUNDE",
            "LIBREVILLE", "BRAZZAVILLE", "BAMAKO", "OUAGADOUGOU",
            "NOUAKCHOTT", "NIAMEY", "TRIPOLI", "ALGIERS", "RABAT", "ACCRA",
            "ABIDJAN", "DAKAR", "FREETOWN", "CONAKRY", "MONROVIA",
            "WASHINGTON", "KINGSTON", "BRIDGETOWN", "MONTEVIDEO",
            "ASUNCION", "SUCRE", "CARACAS", "TEGUCIGALPA", "MANAGUA",
        ]),
        ("Famous Landmarks", [
            "PYRAMID", "SPHINX", "COLOSSEUM", "PARTHENON", "ACROPOLIS",
            "VERSAILLES", "STONEHENGE", "PETRA", "TAJMAHAL", "MACHUPICCHU",
            "BIGBEN", "EIFFELTOWER", "LIBERTY", "OPERAHOUSE", "GOLDENGATE",
            "GRANDCANYON", "NIAGARA", "EVEREST", "FUJI", "VESUVIUS",
            "PAGODA", "OBELISK", "CASTLE", "PALACE", "CATHEDRAL", "MOSQUE",
            "TEMPLE", "FORT", "BRIDGE", "STATUE", "PANTHEON", "ALHAMBRA",
            "HAGIASOPHIA", "NOTREDAME", "WESTMINSTER", "BUCKINGHAM",
            "KREMLIN", "LONDONEYE", "MOUNTRUSHMORE", "TIMESSQUARE",
            "BURJKHALIFA", "PETRONAS", "WHITEHOUSE", "CAPITOL", "EMPIRE",
            "GATEWAY", "LINCOLN", "ELLIS", "ANGKOR", "BOROBUDUR", "POTALA",
            "TREVI", "CHICHENITZA", "REDEEMER", "PISA", "LEANINGTOWER",
            "GIZA", "LUXOR", "KARNAK", "ABUSIMBEL", "MOAI", "KILIMANJARO",
            "MATTERHORN", "MONTBLANC", "ACONCAGUA", "ELBRUS", "OLYMPUS",
            "ETNA", "STROMBOLI", "KILAUEA", "ARARAT", "SINAI", "DENALI",
            "RAINIER", "IGUAZU", "VICTORIA", "WALL", "FORUM",
            "AMPHITHEATER", "BASILICA", "ABBEY", "CHAPEL", "CITADEL",
            "MONUMENT", "MEMORIAL", "MINARET", "MEGALITH", "MONOLITH",
            "RELIC", "BELLTOWER",
        ]),
        ("Transport & Travel", [
            "PLANE", "TRAIN", "BOAT", "SHIP", "CAR", "BUS", "BIKE",
            "BICYCLE", "TRAM", "FERRY", "YACHT", "CANOE", "KAYAK", "RAFT",
            "BALLOON", "GLIDER", "CARRIAGE", "HELICOPTER", "SCOOTER",
            "MOTORBIKE", "AIRPLANE", "JET", "TAXI", "METRO", "MONORAIL",
            "SAILBOAT", "GONDOLA", "RICKSHAW", "TRUCK", "VAN", "WAGON",
            "SLEDGE", "CABLECAR", "AIRCRAFT", "AIRLINER", "JETLINER",
            "PROPELLER", "COCKPIT", "CABIN", "COACH", "TROLLEY", "SUBWAY",
            "TRAMWAY", "LOCOMOTIVE", "STEAMER", "BARGE", "TUGBOAT", "LINER",
            "FREIGHTER", "CATAMARAN", "HOVERCRAFT", "GALLEON", "DHOW",
            "ROWBOAT", "CAMPER", "CARAVAN", "MOTORHOME", "MINIBUS",
            "TAXICAB", "LIMO", "TUKTUK", "SKATES", "SKATEBOARD",
            "SURFBOARD", "CHOPPER", "SEAPLANE", "GYROCOPTER", "ESCALATOR",
            "ELEVATOR", "LIFT", "STAGECOACH", "BUGGY", "ROPEWAY",
            "CHAIRLIFT", "FUNICULAR", "PEDICAB", "TRISHAW", "SLED",
            "SLEIGH", "SNOWMOBILE", "AIRSHIP", "BLIMP", "ZEPPELIN", "DRONE",
            "ROCKET", "SPACESHIP", "SHUTTLE", "CART", "PUNT", "SKI",
            "PADDLE", "CYCLE", "HELMET",
        ]),
        ("Landforms", [
            "MOUNTAIN", "RIVER", "VALLEY", "OCEAN", "DESERT", "FOREST",
            "ISLAND", "LAKE", "GLACIER", "VOLCANO", "CANYON", "PLAINS",
            "HILL", "CLIFF", "BEACH", "COAST", "DELTA", "JUNGLE", "MEADOW",
            "PRAIRIE", "TUNDRA", "PLATEAU", "GORGE", "CAVERN", "WATERFALL",
            "PENINSULA", "LAGOON", "BAY", "CAPE", "ISTHMUS", "MARSH",
            "DUNE", "FJORD", "REEF", "OASIS", "GULF", "CHANNEL", "HARBOR",
            "HAVEN", "COVE", "INLET", "ESTUARY", "SOUND", "STRAIT",
            "BIGHT", "SHOAL", "ATOLL", "ISLET", "ARCHIPELAGO", "HEADLAND",
            "PROMONTORY", "RANGE", "RIDGE", "PEAK", "SUMMIT", "SLOPE",
            "CRAG", "BUTTE", "MESA", "BADLANDS", "WOOD", "GROVE",
            "THICKET", "RAINFOREST", "MANGROVE", "TAIGA", "SAVANNA",
            "SAVANNAH", "SWAMP", "BOG", "FEN", "MOOR", "HEATH", "WETLAND",
            "STREAM", "CREEK", "BROOK", "TRIBUTARY", "CASCADE", "RAPIDS",
            "POND", "BASIN", "SPRING", "GEYSER", "CAVE", "GROTTO",
            "STALACTITE", "STALAGMITE", "PASTURE", "STEPPE", "VELD",
            "PAMPAS", "CRATER", "CALDERA", "BLOWHOLE", "ICEBERG", "FLOE",
            "ICECAP", "PERMAFROST", "CAY", "SANDBAR", "RAVINE", "GULLY",
            "CHASM", "CREVASSE", "BLUFF", "KNOLL", "MOUND", "GLADE",
            "DELL", "MIRE", "QUAGMIRE", "SEA", "WATERSHED", "FIELD",
            "POOL",
        ]),
        ("Travel Items", [
            "SUITCASE", "PASSPORT", "MAP", "COMPASS", "CAMERA", "TICKET",
            "LUGGAGE", "BACKPACK", "WALLET", "SUNHAT", "SUNGLASSES",
            "BOTTLE", "UMBRELLA", "GUIDEBOOK", "ITINERARY", "BINOCULARS",
            "PILLOW", "BLANKET", "SNORKEL", "SANDALS", "BOOTS", "JACKET",
            "RUCKSACK", "TOWEL", "SOAP", "TOOTHBRUSH", "ADAPTER", "DIARY",
            "JOURNAL", "SNEAKERS", "VISA", "BOARDINGPASS", "PHONE",
            "CHARGER", "POWERBANK", "EARPHONES", "HEADPHONES", "TAG",
            "MONEY", "CASH", "COIN", "PURSE", "WATCH", "ALARM", "CLOCK",
            "FLASHLIGHT", "TORCH", "LANTERN", "REPELLENT", "SUNSCREEN",
            "SUNBLOCK", "SUNTAN", "LOTION", "BANDAGE", "PLASTER",
            "MEDICINE", "PILLS", "FLASK", "THERMOS", "MUG", "KNAPSACK",
            "DUFFEL", "HOLDALL", "TOTE", "SATCHEL", "HAT", "CAP", "SCARF",
            "GLOVES", "MITTENS", "COAT", "PARKA", "PONCHO", "RAINCOAT",
            "FLEECE", "JUMPER", "SWEATER", "BELT", "HANDBAG", "BRIEFCASE",
            "GOGGLES", "MASK", "FINS", "FLIPPERS", "STAFF", "POLE", "TENT",
            "SLEEPINGBAG", "STOVE", "LAMP", "ROPE", "MATCHES", "COOLER",
            "ICEPACK", "COUPON", "LENS", "FILM", "TRIPOD", "BOOK", "NOVEL",
            "MAGAZINE", "BROCHURE", "POSTER", "POSTCARD", "STAMP",
            "SOUVENIR", "TRINKET", "GIFT", "EARPLUGS", "EYEMASK",
            "SANITIZER", "WIPES", "TISSUES", "DEODORANT", "RAZOR", "BRUSH",
            "COMB", "MIRROR", "SHAMPOO", "CONDITIONER", "WASHBAG", "CARDS",
        ]),
        ("Maps & Navigation", [
            "NORTH", "SOUTH", "EAST", "WEST", "LATITUDE", "LONGITUDE",
            "EQUATOR", "HEMISPHERE", "ATLAS", "ROUTE", "DIRECTION",
            "BEARING", "MILESTONE", "BORDER", "SCALE", "LEGEND", "CONTOUR",
            "MERIDIAN", "PARALLEL", "HORIZON", "TERRAIN", "COORDINATE",
            "COMPASSROSE", "GLOBE", "NORTHEAST", "NORTHWEST", "SOUTHEAST",
            "SOUTHWEST", "POLAR", "TROPIC", "ARCTIC", "ANTARCTIC",
            "GREENWICH", "TIMEZONE", "ALTITUDE", "ELEVATION", "DISTANCE",
            "MEASURE", "NAUTICAL", "DEGREE", "GRATICULE", "LANDMARK",
            "WAYPOINT", "CHECKPOINT", "MARKER", "BEACON", "INSET", "INDEX",
            "GRID", "SYMBOL", "REGION", "DESTINATION", "ARRIVAL",
            "DEPARTURE", "TRANSIT", "MILEAGE", "GRADIENT", "CHART", "PLOT",
            "PINPOINT", "ORIENTATION", "ORIENT", "CARDINAL", "SATELLITE",
            "RADAR", "SIGNAL", "SIGNPOST", "SIGNBOARD", "ARROW", "CUSTOMS",
            "IMMIGRATION", "TERMINAL", "DEPOT", "HUB", "PORT", "DOCK",
            "PIER", "WHARF", "QUAY", "MARINA", "STATION", "TERMINUS",
            "AIRPORT", "HELIPAD", "RUNWAY", "LANDING", "TAKEOFF",
        ]),
        ("Adventure Words", [
            "EXPLORE", "JOURNEY", "VOYAGE", "ADVENTURE", "TREK", "HIKE",
            "DISCOVER", "WANDER", "EXPEDITION", "SAFARI", "CAMP",
            "CAMPFIRE", "TRAIL", "PATH", "GUIDE", "ESCAPE", "ROAM",
            "QUEST", "DISCOVERY", "WILDERNESS", "FRONTIER", "EXCURSION",
            "OUTING", "TOUR", "TOURIST", "TRAVEL", "TRAVELER", "NOMAD",
            "EXPLORER", "VOYAGER", "WANDERLUST", "BACKPACKING", "HIKING",
            "TREKKING", "CLIMBING", "CAMPING", "ASCEND", "DESCEND",
            "CONQUER", "SIGHTSEE", "SIGHTSEEING", "RAMBLE", "STROLL",
            "AMBLE", "TRAMP", "TRUDGE", "UNEARTH", "FIND", "SEEK", "SPOT",
            "DIVE", "SWIM", "SURF", "PARAGLIDE", "PARACHUTE", "BUNGEE",
            "SKYDIVE", "SCUBA", "SKATE", "RIDE", "PEDAL", "FISH", "HUNT",
            "FORAGE", "CLIMB", "RAPPEL", "ABSEIL", "BOULDER", "THRILL",
            "DARING", "BRAVE", "BOLD", "FEARLESS", "COURAGE", "MARVEL",
            "WONDER", "AWE", "BEHOLD", "RELAX", "UNWIND", "REST", "LOUNGE",
            "BASK", "PICNIC", "FEAST", "TASTE", "SAVOR", "PHOTO", "SNAP",
            "CAPTURE", "WAYFARER", "PILGRIM", "PILGRIMAGE", "SETTLER",
            "PIONEER", "SCOUT", "CONVOY", "ENTOURAGE", "NAVIGATE", "STEER",
            "PILOT", "CAPTAIN", "CREW", "HELM", "ANCHOR", "ODYSSEY",
            "TREASURE",
        ]),
        ("Currencies", [
            "DOLLAR", "EURO", "POUND", "YEN", "YUAN", "RUPEE", "RUBLE",
            "PESO", "FRANC", "KRONA", "KRONE", "RAND", "SHEKEL", "DINAR",
            "DIRHAM", "LIRA", "WON", "RIAL", "REAL", "ZLOTY", "FORINT",
            "KORUNA", "RUPIAH", "BAHT", "QUETZAL", "COLON", "HRYVNIA",
            "LEK", "DONG", "DRACHMA", "GUARANI", "PULA", "BOLIVAR", "TAKA",
            "NAIRA", "LEV", "LEU", "SOM", "MANAT",
        ]),
        ("World Regions & Seas", [
            "SCANDINAVIA", "BALKANS", "BALTIC", "IBERIA", "ANATOLIA",
            "MESOPOTAMIA", "PATAGONIA", "AMAZONIA", "SIBERIA", "CAUCASUS",
            "SAHEL", "MAGHREB", "INDIES", "POLYNESIA", "MICRONESIA",
            "MELANESIA", "CARIBBEAN", "MEDITERRANEAN", "ANTARCTICA",
            "PACIFIC", "ATLANTIC", "BERING", "AEGEAN", "IONIAN",
            "ADRIATIC", "TYRRHENIAN", "CASPIAN", "ARAL", "BARENTS",
            "SARGASSO", "TASMAN", "SCOTIA", "CORAL", "SUBCONTINENT",
        ]),
        ("Rivers, Deserts & Mountains", [
            "SAHARA", "GOBI", "KALAHARI", "NAMIB", "ATACAMA", "MOJAVE",
            "SONORAN", "TAKLAMAKAN", "THAR", "ARABIAN", "KARAKUM", "NEGEV",
            "SIMPSON", "NILE", "AMAZON", "MISSISSIPPI", "YANGTZE", "GANGES",
            "DANUBE", "NIGER", "MEKONG", "LENA", "YENISEI", "VOLGA",
            "RHINE", "SEINE", "THAMES", "INDUS", "TIBER", "ZAMBEZI",
            "ORINOCO", "MURRAY", "EUPHRATES", "TIGRIS", "COLORADO", "AMUR",
            "IRRAWADDY", "BRAHMAPUTRA", "PARANA", "YUKON", "MACKENZIE",
            "ALPS", "ANDES", "ROCKIES", "HIMALAYAS", "URALS", "PYRENEES",
            "APPALACHIAN", "DOLOMITES", "SIERRA", "RUWENZORI",
        ]),
    ])
    trivia_easy = [
        {"q": "The Eiffel Tower is in which city?",
         "options": ["Paris", "London", "Rome"], "answer": "Paris"},
        {"q": "Which country is called the Land of the Rising Sun?",
         "options": ["Japan", "China", "Thailand"], "answer": "Japan"},
        {"q": "The Great Pyramids are found in which country?",
         "options": ["Egypt", "Mexico", "Greece"], "answer": "Egypt"},
        {"q": "Which is the largest ocean on Earth?",
         "options": ["Pacific", "Atlantic", "Indian"], "answer": "Pacific"},
        {"q": "What document do you need to enter another country?",
         "options": ["A passport", "A ticket", "A map"], "answer": "A passport"},
        {"q": "Which famous landmark stands in India?",
         "options": ["Taj Mahal", "Great Wall", "Colosseum"], "answer": "Taj Mahal"},
        {"q": "Which is the coldest continent?",
         "options": ["Antarctica", "Africa", "Asia"], "answer": "Antarctica"},
        {"q": "Which mode of travel flies high in the sky?",
         "options": ["An airplane", "A ship", "A train"], "answer": "An airplane"},
        {"q": "The Statue of Liberty is in which city?",
         "options": ["New York", "Paris", "Tokyo"], "answer": "New York"},
        {"q": "Which animal is a symbol of Australia?",
         "options": ["The kangaroo", "The panda", "The eagle"], "answer": "The kangaroo"},
        {"q": "Which currency is used across much of Europe?",
         "options": ["The euro", "The dollar", "The pound"], "answer": "The euro"},
        {"q": "Which country is shaped like a boot?",
         "options": ["Italy", "Spain", "Greece"], "answer": "Italy"},
    ]
    phrase_medium = [
        {"prompt": "A journey of a thousand miles begins with a single ____",
         "answer": "Step"},
        {"prompt": "The world is your ____", "answer": "Oyster"},
        {"prompt": "Not all who wander are ____", "answer": "Lost"},
        {"prompt": "Travel broadens the ____", "answer": "Mind"},
        {"prompt": "Home away from ____", "answer": "Home"},
        {"prompt": "The road less ____", "answer": "Travelled"},
        {"prompt": "Bon ____ (French for 'good trip')", "answer": "Voyage"},
        {"prompt": "Hit the road, ____", "answer": "Jack"},
        {"prompt": "The seven ____ of the world", "answer": "Wonders"},
    ]
    trivia_open = [
        {"q": "Name the famous iron tower in Paris.", "answer": "Eiffel Tower"},
        {"q": "What is the capital city of Japan?", "answer": "Tokyo"},
        {"q": "Which booklet proves your identity for international travel?",
         "answer": "A passport"},
        {"q": "Name the largest ocean on Earth.", "answer": "The Pacific Ocean"},
        {"q": "What tool uses a magnetic needle to show direction?",
         "answer": "A compass"},
        {"q": "Which is the largest hot desert in the world?", "answer": "The Sahara"},
        {"q": "Name the long wall that stretches across northern China.",
         "answer": "The Great Wall of China"},
        {"q": "What do you call someone who travels for pleasure to see places?",
         "answer": "A tourist"},
    ]
    crossword = [
        ("PARIS", "City home to the Eiffel Tower"),
        ("JAPAN", "Land of the Rising Sun"),
        ("NILE", "Great river that flows through Egypt"),
        ("PLANE", "Vehicle that flies between cities"),
        ("PASSPORT", "Travel booklet that proves your identity"),
        ("COMPASS", "Tool whose needle always points north"),
        ("EGYPT", "Country of pyramids and pharaohs"),
        ("EVEREST", "World's tallest mountain"),
        ("OCEAN", "Vast body of salty water"),
        ("ISLAND", "Land entirely surrounded by water"),
        ("CAMERA", "Device used to take holiday photos"),
        ("ATLAS", "Book full of maps"),
        ("DESERT", "Dry, sandy land like the Sahara"),
        ("ITALY", "Boot-shaped country in Europe"),
        ("SAFARI", "Wildlife-watching trip, common in Africa"),
        ("GLACIER", "Slow-moving river of ice"),
        ("TOKYO", "Capital city of Japan"),
        ("VOLCANO", "Mountain that can erupt with lava"),
        ("TICKET", "Pass that lets you board a train or plane"),
        ("AMAZON", "Mighty river and rainforest in South America"),
        ("BALLOON", "Colourful craft that floats in the sky"),
        ("CANAL", "Waterway like the ones of Venice"),
        ("TAJMAHAL", "Famous white marble tomb in India"),
        ("VIENNA", "Capital of Austria, the city of music"),
        ("FERRY", "Boat that carries people across water"),
        ("RUSSIA", "Largest country in the world by area"),
        ("BEACH", "Sandy shore by the sea"),
        ("MAP", "Drawing that shows countries and roads"),
        ("SAHARA", "Vast desert in northern Africa"),
        ("KENYA", "East African country famed for safaris"),
    ]
    remedies = [
        {"condition": "Motion Queasiness",
         "text": "Suck on a small piece of fresh ginger or sip ginger-lemon "
                 "water, and look toward the distant horizon. Keep cool air on "
                 "your face and avoid reading or screens while moving. Small, "
                 "dry snacks and steady sips of water also help."},
        {"condition": "Travel Constipation",
         "text": "Start the day with a glass of warm water, and eat fruit like "
                 "papaya or prunes when you can. Move around and walk between "
                 "journeys rather than sitting still for long. A spoon of "
                 "triphala, a traditional three-fruit blend, in warm water at "
                 "night is a gentle aid."},
        {"condition": "Jet Lag & Broken Sleep",
         "text": "Get some morning daylight at your new destination to reset "
                 "your body clock, and take short naps rather than one long "
                 "sleep. Sip warm milk with a pinch of nutmeg at night and ease "
                 "into local meal times. Drink plenty of water along the way."},
        {"condition": "Travel Headache",
         "text": "Sip a glass of water, eat a small snack, and rest in a cool, "
                 "quiet spot; a cup of ginger tea can help. A cool cloth on the "
                 "forehead brings relief. Travel headaches often follow skipped "
                 "meals, heat, or poor sleep."},
        {"condition": "Stiff Legs & Feet",
         "text": "Stand up and stretch every hour or so, and roll your ankles "
                 "and calves gently. On arrival, soak tired feet in warm water "
                 "with a little salt, then massage with sesame oil. Cushioned "
                 "shoes and a short walk get the blood moving again."},
        {"condition": "Coconut Water",
         "text": "Drink fresh tender coconut water straight from the coconut. "
                 "It naturally rehydrates, cools the body, and is gentle on the "
                 "stomach after a long journey."},
        {"condition": "Barley Water",
         "text": "Boil barley in plenty of water, strain, and add a squeeze of "
                 "lemon. This cooling, light drink is a traditional help for "
                 "summer hydration and urinary comfort."},
    ]
    coloring = ["car", "sun", "bird", "butterfly", "leaf", "star"]
    return {
        "word_pools": _dedup_pools(word_pools),
        "trivia_easy": trivia_easy, "phrase_medium": phrase_medium,
        "trivia_open": trivia_open, "crossword": crossword,
        "remedies": remedies, "remedies_title": "Home Remedies & Wellness Wisdom",
        "coloring": coloring,
    }


def _dedup_pools(pools):
    seen, out = set(), OrderedDict()
    for cat, words in pools.items():
        clean = []
        for w in words:
            wu = w.upper()
            if wu.isalpha() and 3 <= len(wu) <= 13 and wu not in seen:
                seen.add(wu); clean.append(wu)
        out[cat] = clean
    return out


BANKS = {"travel": build}
